import test from 'node:test';
import assert from 'node:assert/strict';
import {canonical,sharedData,mergeCatalog,validateCatalog} from '../shared/catalog.js';
import {makeGas,initialData} from './gas-harness.mjs';
const clone=x=>structuredClone(x);
function setup() {
 const gas=makeGas({legacy:initialData()});
 const token=gas.post({action:'login',password:'test-password-12345'}).token;
 const first=gas.get();
 const save=(data,rev=first.revision,id=crypto.randomUUID())=>gas.post({action:'saveData',token,data,baseRevision:rev,requestId:id});
 return {gas,first,save,token};
}
function page(data){return data.categories.find(c=>c.rows?.length && c.columns?.length);}
test('all supplied demo data meets schema and metadata survives',()=>{const d=initialData();validateCatalog(d);assert.ok(d.categories.length>10);const c=d.categories[0];c.icon='star';c.slug='test';c.lastUpdated='today';assert.equal(sharedData(d).categories[0].icon,'star');});
test('content comparison notices a price change with identical row counts',()=>{let a=initialData(),b=clone(a);page(b).rows[0].cells.price=15;assert.notEqual(canonical(a),canonical(b));});
test('different cells merge; same cell conflicts; same value converges',()=>{const b=sharedData(initialData()),l=clone(b),r=clone(b);page(l).rows[0].cells.x='L';page(r).rows[0].cells.y='R';let m=mergeCatalog(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(page(m.data).rows[0].cells.x,'L');assert.equal(page(m.data).rows[0].cells.y,'R');page(r).rows[0].cells.x='R';assert.equal(mergeCatalog(b,l,r).conflicts.length,1);page(r).rows[0].cells.x='L';assert.equal(mergeCatalog(b,l,r).conflicts.length,0);});
test('simultaneous row additions are retained',()=>{const b=initialData(),l=clone(b),r=clone(b);page(l).rows.push({id:'left',cells:{name:'L'}});page(r).rows.push({id:'right',cells:{name:'R'}});const m=mergeCatalog(b,l,r);assert.equal(m.conflicts.length,0);assert.equal(page(m.data).rows.length,page(b).rows.length+2);});
test('delete versus edit conflicts; concurrent reorder conflicts',()=>{const b=initialData(),l=clone(b),r=clone(b);page(l).rows.shift();page(r).rows[0].cells.name='changed';assert.ok(mergeCatalog(b,l,r).conflicts.length);const x=clone(b),y=clone(b);page(x).rows.reverse();const rows=page(y).rows;[rows[0],rows[1]]=[rows[1],rows[0]];assert.ok(mergeCatalog(b,x,y).conflicts.some(x=>x.endsWith('порядок')));});
test('invalid cycles, duplicate IDs, dangling references and hostile keys rejected',()=>{const d=initialData();d.categories[0].parentId=d.categories[0].id;assert.throws(()=>validateCatalog(d));const x=initialData();x.categories.push(x.categories[0]);assert.throws(()=>validateCatalog(x));const y=initialData();y.categories[0].parentId='missing';assert.throws(()=>validateCatalog(y));const z=initialData();z.categories[0].rows=[{id:'a',cells:JSON.parse('{"__proto__":"x"}')}];assert.throws(()=>validateCatalog(z));});
test('anonymous writes, wrong passwords, forged tokens and mail action rejected',()=>{const {gas,first}=setup();assert.equal(gas.post({action:'saveData',data:first.data}).status,'unauthorized');assert.equal(gas.post({action:'login',password:'wrong'}).status,'unauthorized');assert.equal(gas.post({action:'sendReport',token:'forged'}).status,'unauthorized');assert.equal(gas.get().revision,first.revision);});
test('CAS prevents stale overwrite, independent edits merge and commit',()=>{const {first,save,gas}=setup(),a=clone(first.data),b=clone(first.data);page(a).rows[0].cells.x='A';page(b).rows[0].cells.y='B';const one=save(a);assert.equal(one.status,'ok');const conflict=save(b);assert.equal(conflict.status,'conflict');const m=mergeCatalog(first.data,b,conflict.data);assert.equal(m.conflicts.length,0);assert.equal(save(m.data,conflict.revision).status,'ok');assert.equal(page(gas.get().data).rows[0].cells.x,'A');assert.equal(page(gas.get().data).rows[0].cells.y,'B');});
test('identical request replay is idempotent even after later commits',()=>{const {first,save,gas}=setup();const id=crypto.randomUUID(),a=clone(first.data);page(a).rows[0].cells.x='A';const one=save(a,first.revision,id);const b=clone(one.data);page(b).rows[0].cells.y='B';const two=save(b,one.revision);const replay=save(a,first.revision,id);assert.equal(replay.status,'ok');assert.equal(replay.revision,two.revision);assert.equal(gas.get().revision,two.revision);assert.equal(save(b,first.revision,id).status,'error');});
test('write and pointer failures preserve last committed snapshot',()=>{const {first,save,gas}=setup();const data=clone(first.data);page(data).rows[0].cells.x='new';gas.failNextWrite();assert.equal(save(data).status,'error');assert.equal(canonical(gas.get().data),canonical(first.data));gas.failNextPointer();assert.equal(save(data).status,'error');assert.equal(canonical(gas.get().data),canonical(first.data));assert.equal(save(data).status,'ok');});
test('lightweight version check avoids reading catalog and releases locks',()=>{const {gas,first,save}=setup();assert.equal(gas.get({revision:String(first.revision)}).status,'unchanged');gas.holdLock();assert.equal(save(first.data).status,'busy');gas.releaseLock();assert.equal(save(first.data).status,'ok');});
test('empty catalog stays empty, initialization cannot replace a populated table',()=>{const gas=makeGas();assert.equal(gas.get().status,'empty');const token=gas.post({action:'login',password:'test-password-12345'}).token;const data=initialData();data.categories=[];data.changelog=[];const req={action:'saveData',token,baseRevision:0,requestId:crypto.randomUUID(),data};assert.equal(gas.post(req).status,'ok');assert.equal(gas.get().data.categories.length,0);req.requestId=crypto.randomUUID();assert.equal(gas.post(req).status,'conflict');});
test('password rotation invalidates existing sessions',()=>{const {gas,first,save}=setup();gas.properties.set('ADMIN_PASSWORD','different-password-67890');assert.equal(save(first.data).status,'unauthorized');});
test('legacy source is retained byte for byte by setup',()=>{const data=initialData(),gas=makeGas({legacy:data});assert.equal(gas.sheets.get('__DATA__').getRange(1,1).getValues()[0][0],JSON.stringify(data));const before=gas.get().revision;gas.context.setup();assert.equal(gas.get().revision,before);assert.ok(!JSON.stringify(gas.get()).includes('adminPasswordHash'));});
test('login rate limit rejects excessive attempts',()=>{const gas=makeGas();for(let i=0;i<20;i++)gas.post({action:'login',password:'bad'});assert.match(gas.post({action:'login',password:'bad'}).error,/много/);});
